# Generated by Django 3.2.25 on 2024-10-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumtask',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forumtask',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
