# Generated by Django 3.2.25 on 2024-10-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maintenance', '0003_auto_20241020_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumtask',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forumtask',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forumtask',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forumtask',
            name='date_reported',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
